setwd("C:/Users/Administrator/Desktop/R")
library(openxlsx)
d3.1=read.xlsx("mvstats5.xlsx","d3.1",rowNames = T);d3.1
barplot(apply(d3.1,1,mean))
barplot(apply(d3.1,1,mean),las=3)
barplot(apply(d3.1,2,mean))
barplot(apply(d3.1,2,mean),col=1:8)
barplot(apply(d3.1[2:8,],1,mean))
barplot(apply(d3.1,1,mean),col=1:9)
boxplot(d3.1)
boxplot(d3.1,horizontal = T ,las=1)
stars(d3.1)
stars(d3.1,key.loc = c(13,1.8))
stars(d3.1,full = F,key.loc = c(13,1.8))
stars(d3.1,draw.segments = T,key.loc = c(13,1.8))
stars(d3.1,full = F,draw.segments = T,key.loc = c(13,1.8))
install.packages("aplpack")
library(aplpack)
faces(d3.1,ncol.plot = 7)
faces(d3.1[,2:8])
faces(d3.1[,2:8],ncol.plot = 7)
faces(d3.1[c(1,9,19,28,29,30),])

Case3<-read.xlsx('mvcase5.xlsx','Case3',rowNames = T);head(Case3)
summary(Case3)
boxplot(Case3)
rm<-apply(Case3,1,mean);rm
barplot(rm,las = 3)
cm<-apply(Case3,2,mean);cm
barplot(cm,horiz = T)
stars(Case3,key.loc = c(8,2))
stars(Case3,draw.segments = T,key.loc = c(8,2))
library(aplpack)
faces(Case3)
library(msaR)
msa.andrews(Case3)
